// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AssetResponse
 */
export type AssetResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Original Filename
     */
    original_filename: string;
    /**
     * Added At
     */
    added_at: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Provenance
     */
    provenance?: {
        [key: string]: unknown;
    } | null;
    /**
     * Project
     */
    project?: string | null;
};

/**
 * Body_assemble_assemble_post
 */
export type Body_assemble_assemble_post = {
    /**
     * Clip Asset Ids
     */
    clip_asset_ids: Array<string>;
    /**
     * Music Asset Ids
     */
    music_asset_ids: Array<string>;
    /**
     * Sound Effect Asset Ids
     */
    sound_effect_asset_ids?: Array<string>;
    /**
     * Video Crossfade Duration
     */
    video_crossfade_duration?: number;
    /**
     * Music Crossfade Duration
     */
    music_crossfade_duration?: number;
    /**
     * Music Edge Fade Duration
     */
    music_edge_fade_duration?: number;
    /**
     * Music Gap Duration
     */
    music_gap_duration?: number;
};

/**
 * Body_generate_image_generate_image_post
 */
export type Body_generate_image_generate_image_post = {
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Reference Image
     */
    reference_image?: Blob | File | null;
    /**
     * Strength
     */
    strength?: number;
    /**
     * Model
     */
    model?: string;
};

/**
 * Body_generate_music_generate_music_post
 */
export type Body_generate_music_generate_music_post = {
    /**
     * Prompt
     */
    prompt?: string;
    /**
     * Lyrics
     */
    lyrics?: string;
    /**
     * Duration
     */
    duration?: number;
    /**
     * Thinking
     */
    thinking?: boolean;
    /**
     * Instrumental
     */
    instrumental?: boolean;
    /**
     * Model
     */
    model?: string;
    /**
     * Task Type
     */
    task_type?: string;
    /**
     * Src Audio File
     */
    src_audio_file?: Blob | File | null;
    /**
     * Src Audio Asset Id
     */
    src_audio_asset_id?: string | null;
    /**
     * Reference Audio File
     */
    reference_audio_file?: Blob | File | null;
    /**
     * Reference Audio Asset Id
     */
    reference_audio_asset_id?: string | null;
    /**
     * Cover Strength
     */
    cover_strength?: number;
    /**
     * Repainting Start
     */
    repainting_start?: number;
    /**
     * Repainting End
     */
    repainting_end?: number;
};

/**
 * Body_generate_sound_effect_generate_sound_effect_post
 */
export type Body_generate_sound_effect_generate_sound_effect_post = {
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Duration
     */
    duration?: number;
};

/**
 * Body_library_add_library_post
 */
export type Body_library_add_library_post = {
    /**
     * Upload
     */
    upload: Blob | File;
    /**
     * Kind
     */
    kind?: string;
    /**
     * Tags
     */
    tags?: string;
    /**
     * Project
     */
    project?: string | null;
};

/**
 * Body_mask_preview_mask_preview_post
 */
export type Body_mask_preview_mask_preview_post = {
    /**
     * Input File
     */
    input_file: Blob | File;
    /**
     * Mask Threshold
     */
    mask_threshold?: number;
    /**
     * Feather
     */
    feather?: number;
};

/**
 * Body_rename_project_projects_rename_post
 */
export type Body_rename_project_projects_rename_post = {
    /**
     * Old
     */
    old: string;
    /**
     * New
     */
    new: string;
};

/**
 * Body_render_photo_render_photo_post
 */
export type Body_render_photo_render_photo_post = {
    /**
     * Input File
     */
    input_file?: Blob | File | null;
    /**
     * Input Asset Id
     */
    input_asset_id?: string | null;
    /**
     * Effect
     */
    effect: Array<string>;
    /**
     * Mask
     */
    mask?: Blob | File | null;
    /**
     * Mask Prompt
     */
    mask_prompt?: string | null;
    /**
     * Unmasked Effects
     */
    unmasked_effects?: Array<string>;
    /**
     * Duration
     */
    duration?: number;
    /**
     * Fps
     */
    fps?: number;
    /**
     * Speed
     */
    speed?: number;
    /**
     * Rain Count
     */
    rain_count?: number | null;
    /**
     * Rain Opacity
     */
    rain_opacity?: number | null;
    /**
     * Snow Count
     */
    snow_count?: number | null;
    /**
     * Snow Opacity
     */
    snow_opacity?: number | null;
    /**
     * Dust Count
     */
    dust_count?: number | null;
    /**
     * Dust Opacity
     */
    dust_opacity?: number | null;
    /**
     * Ripple Amplitude
     */
    ripple_amplitude?: number | null;
    /**
     * Ripple Wavelength
     */
    ripple_wavelength?: number | null;
    /**
     * Sway Amplitude
     */
    sway_amplitude?: number | null;
    /**
     * Sway Freq
     */
    sway_freq?: number | null;
    /**
     * Wind Amplitude
     */
    wind_amplitude?: number | null;
    /**
     * Wind Gustiness
     */
    wind_gustiness?: number | null;
    /**
     * Flicker Strength
     */
    flicker_strength?: number | null;
    /**
     * Smoke Opacity
     */
    smoke_opacity?: number | null;
    /**
     * Vapor Opacity
     */
    vapor_opacity?: number | null;
    /**
     * Feather
     */
    feather?: number;
    /**
     * Apply Grade
     */
    apply_grade?: boolean;
    /**
     * Grade Strength
     */
    grade_strength?: number;
    /**
     * Grain
     */
    grain?: number;
    /**
     * Also Gif
     */
    also_gif?: boolean;
    /**
     * Loop Duration
     */
    loop_duration?: number | null;
};

/**
 * Body_render_video_render_video_post
 */
export type Body_render_video_render_video_post = {
    /**
     * Input File
     */
    input_file: Blob | File;
    /**
     * Mask
     */
    mask?: Blob | File | null;
    /**
     * Still Frame Index
     */
    still_frame_index?: number;
    /**
     * Blend Frames
     */
    blend_frames?: number;
    /**
     * Auto Trim
     */
    auto_trim?: boolean;
    /**
     * Mask Threshold
     */
    mask_threshold?: number;
    /**
     * Feather
     */
    feather?: number;
    /**
     * Apply Grade
     */
    apply_grade?: boolean;
    /**
     * Grade Strength
     */
    grade_strength?: number;
    /**
     * Grain
     */
    grain?: number;
    /**
     * Also Gif
     */
    also_gif?: boolean;
    /**
     * Loop Duration
     */
    loop_duration?: number | null;
};

/**
 * Body_save_job_jobs__job_id__save_post
 */
export type Body_save_job_jobs__job_id__save_post = {
    /**
     * Project
     */
    project?: string | null;
};

/**
 * Body_semantic_mask_mask_semantic_post
 */
export type Body_semantic_mask_mask_semantic_post = {
    /**
     * Image
     */
    image: Blob | File;
    /**
     * Prompt
     */
    prompt: string;
};

/**
 * Body_set_asset_project_library__asset_id__project_post
 */
export type Body_set_asset_project_library__asset_id__project_post = {
    /**
     * Project
     */
    project?: string | null;
};

/**
 * CapabilitiesResponse
 */
export type CapabilitiesResponse = {
    /**
     * Semantic Mask
     */
    semantic_mask: boolean;
    /**
     * Music Generation
     */
    music_generation: boolean;
    /**
     * Sound Effect Generation
     */
    sound_effect_generation: boolean;
    /**
     * Image Generation
     */
    image_generation: boolean;
    /**
     * Image Generation Models
     */
    image_generation_models?: Array<string>;
    /**
     * Music Generation Models
     */
    music_generation_models?: Array<string>;
    /**
     * Music Remix Models
     */
    music_remix_models?: Array<string>;
    /**
     * Configured
     */
    configured?: {
        [key: string]: boolean;
    };
    /**
     * Version
     */
    version?: string;
    /**
     * Services
     */
    services?: Array<ServiceStatus>;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobResponse
 */
export type JobResponse = {
    /**
     * Job Id
     */
    job_id: string;
};

/**
 * JobStatusResponse
 */
export type JobStatusResponse = {
    /**
     * Job Id
     */
    job_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Output Path
     */
    output_path?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Can Save
     */
    can_save?: boolean;
    /**
     * Saved Asset Id
     */
    saved_asset_id?: string | null;
};

/**
 * ServiceStatus
 *
 * Per-satellite detail behind the capability booleans below.
 *
 * The bools answer "can the UI offer this feature". These answer "what is
 * actually going on", which is what the Setup tab and `cinemagraph doctor`
 * need in order to tell someone what to do about it -- including which env
 * var configures it, so the answer doesn't require reading
 * docker-compose.yml.
 */
export type ServiceStatus = {
    /**
     * Name
     */
    name: string;
    /**
     * Env Var
     */
    env_var: string;
    /**
     * Configured
     */
    configured: boolean;
    /**
     * Reachable
     */
    reachable: boolean;
    /**
     * Health
     */
    health?: {
        [key: string]: unknown;
    } | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type healthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type healthHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type capabilitiesCapabilitiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/capabilities';
};

export type capabilitiesCapabilitiesGetResponses = {
    /**
     * Successful Response
     */
    200: CapabilitiesResponse;
};

export type capabilitiesCapabilitiesGetResponse = capabilitiesCapabilitiesGetResponses[keyof capabilitiesCapabilitiesGetResponses];

export type listEffectsEffectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/effects';
};

export type listEffectsEffectsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type renderVideoRenderVideoPostData = {
    body: Body_render_video_render_video_post;
    path?: never;
    query?: never;
    url: '/render/video';
};

export type renderVideoRenderVideoPostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type renderVideoRenderVideoPostError = renderVideoRenderVideoPostErrors[keyof renderVideoRenderVideoPostErrors];

export type renderVideoRenderVideoPostResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type renderVideoRenderVideoPostResponse = renderVideoRenderVideoPostResponses[keyof renderVideoRenderVideoPostResponses];

export type renderPhotoRenderPhotoPostData = {
    body: Body_render_photo_render_photo_post;
    path?: never;
    query?: never;
    url: '/render/photo';
};

export type renderPhotoRenderPhotoPostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type renderPhotoRenderPhotoPostError = renderPhotoRenderPhotoPostErrors[keyof renderPhotoRenderPhotoPostErrors];

export type renderPhotoRenderPhotoPostResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type renderPhotoRenderPhotoPostResponse = renderPhotoRenderPhotoPostResponses[keyof renderPhotoRenderPhotoPostResponses];

export type maskPreviewMaskPreviewPostData = {
    body: Body_mask_preview_mask_preview_post;
    path?: never;
    query?: never;
    url: '/mask-preview';
};

export type maskPreviewMaskPreviewPostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type maskPreviewMaskPreviewPostError = maskPreviewMaskPreviewPostErrors[keyof maskPreviewMaskPreviewPostErrors];

export type maskPreviewMaskPreviewPostResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type maskPreviewMaskPreviewPostResponse = maskPreviewMaskPreviewPostResponses[keyof maskPreviewMaskPreviewPostResponses];

export type jobStatusJobsJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}';
};

export type jobStatusJobsJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type jobStatusJobsJobIdGetError = jobStatusJobsJobIdGetErrors[keyof jobStatusJobsJobIdGetErrors];

export type jobStatusJobsJobIdGetResponses = {
    /**
     * Successful Response
     */
    200: JobStatusResponse;
};

export type jobStatusJobsJobIdGetResponse = jobStatusJobsJobIdGetResponses[keyof jobStatusJobsJobIdGetResponses];

export type jobFileJobsJobIdFileGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}/file';
};

export type jobFileJobsJobIdFileGetErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type jobFileJobsJobIdFileGetError = jobFileJobsJobIdFileGetErrors[keyof jobFileJobsJobIdFileGetErrors];

export type jobFileJobsJobIdFileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type saveJobJobsJobIdSavePostData = {
    body?: Body_save_job_jobs__job_id__save_post;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/jobs/{job_id}/save';
};

export type saveJobJobsJobIdSavePostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type saveJobJobsJobIdSavePostError = saveJobJobsJobIdSavePostErrors[keyof saveJobJobsJobIdSavePostErrors];

export type saveJobJobsJobIdSavePostResponses = {
    /**
     * Successful Response
     */
    200: AssetResponse;
};

export type saveJobJobsJobIdSavePostResponse = saveJobJobsJobIdSavePostResponses[keyof saveJobJobsJobIdSavePostResponses];

export type libraryListLibraryGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Kind
         */
        kind?: string | null;
        /**
         * Tag
         */
        tag?: string | null;
        /**
         * Project
         */
        project?: string | null;
    };
    url: '/library';
};

export type libraryListLibraryGetErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type libraryListLibraryGetError = libraryListLibraryGetErrors[keyof libraryListLibraryGetErrors];

export type libraryListLibraryGetResponses = {
    /**
     * Response Library List Library Get
     *
     * Successful Response
     */
    200: Array<AssetResponse>;
};

export type libraryListLibraryGetResponse = libraryListLibraryGetResponses[keyof libraryListLibraryGetResponses];

export type libraryAddLibraryPostData = {
    body: Body_library_add_library_post;
    path?: never;
    query?: never;
    url: '/library';
};

export type libraryAddLibraryPostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type libraryAddLibraryPostError = libraryAddLibraryPostErrors[keyof libraryAddLibraryPostErrors];

export type libraryAddLibraryPostResponses = {
    /**
     * Successful Response
     */
    200: AssetResponse;
};

export type libraryAddLibraryPostResponse = libraryAddLibraryPostResponses[keyof libraryAddLibraryPostResponses];

export type setAssetProjectLibraryAssetIdProjectPostData = {
    body?: Body_set_asset_project_library__asset_id__project_post;
    path: {
        /**
         * Asset Id
         */
        asset_id: string;
    };
    query?: never;
    url: '/library/{asset_id}/project';
};

export type setAssetProjectLibraryAssetIdProjectPostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type setAssetProjectLibraryAssetIdProjectPostError = setAssetProjectLibraryAssetIdProjectPostErrors[keyof setAssetProjectLibraryAssetIdProjectPostErrors];

export type setAssetProjectLibraryAssetIdProjectPostResponses = {
    /**
     * Successful Response
     */
    200: AssetResponse;
};

export type setAssetProjectLibraryAssetIdProjectPostResponse = setAssetProjectLibraryAssetIdProjectPostResponses[keyof setAssetProjectLibraryAssetIdProjectPostResponses];

export type listProjectsProjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects';
};

export type listProjectsProjectsGetResponses = {
    /**
     * Response List Projects Projects Get
     *
     * Successful Response
     */
    200: Array<string>;
};

export type listProjectsProjectsGetResponse = listProjectsProjectsGetResponses[keyof listProjectsProjectsGetResponses];

export type renameProjectProjectsRenamePostData = {
    body: Body_rename_project_projects_rename_post;
    path?: never;
    query?: never;
    url: '/projects/rename';
};

export type renameProjectProjectsRenamePostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type renameProjectProjectsRenamePostError = renameProjectProjectsRenamePostErrors[keyof renameProjectProjectsRenamePostErrors];

export type renameProjectProjectsRenamePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type deleteProjectProjectsNameDeleteData = {
    body?: never;
    path: {
        /**
         * Name
         */
        name: string;
    };
    query?: never;
    url: '/projects/{name}';
};

export type deleteProjectProjectsNameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type deleteProjectProjectsNameDeleteError = deleteProjectProjectsNameDeleteErrors[keyof deleteProjectProjectsNameDeleteErrors];

export type deleteProjectProjectsNameDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type libraryRemoveLibraryAssetIdDeleteData = {
    body?: never;
    path: {
        /**
         * Asset Id
         */
        asset_id: string;
    };
    query?: never;
    url: '/library/{asset_id}';
};

export type libraryRemoveLibraryAssetIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type libraryRemoveLibraryAssetIdDeleteError = libraryRemoveLibraryAssetIdDeleteErrors[keyof libraryRemoveLibraryAssetIdDeleteErrors];

export type libraryRemoveLibraryAssetIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type libraryGetLibraryAssetIdGetData = {
    body?: never;
    path: {
        /**
         * Asset Id
         */
        asset_id: string;
    };
    query?: never;
    url: '/library/{asset_id}';
};

export type libraryGetLibraryAssetIdGetErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type libraryGetLibraryAssetIdGetError = libraryGetLibraryAssetIdGetErrors[keyof libraryGetLibraryAssetIdGetErrors];

export type libraryGetLibraryAssetIdGetResponses = {
    /**
     * Successful Response
     */
    200: AssetResponse;
};

export type libraryGetLibraryAssetIdGetResponse = libraryGetLibraryAssetIdGetResponses[keyof libraryGetLibraryAssetIdGetResponses];

export type libraryFileLibraryAssetIdFileGetData = {
    body?: never;
    path: {
        /**
         * Asset Id
         */
        asset_id: string;
    };
    query?: never;
    url: '/library/{asset_id}/file';
};

export type libraryFileLibraryAssetIdFileGetErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type libraryFileLibraryAssetIdFileGetError = libraryFileLibraryAssetIdFileGetErrors[keyof libraryFileLibraryAssetIdFileGetErrors];

export type libraryFileLibraryAssetIdFileGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type semanticMaskMaskSemanticPostData = {
    body: Body_semantic_mask_mask_semantic_post;
    path?: never;
    query?: never;
    url: '/mask/semantic';
};

export type semanticMaskMaskSemanticPostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type semanticMaskMaskSemanticPostError = semanticMaskMaskSemanticPostErrors[keyof semanticMaskMaskSemanticPostErrors];

export type semanticMaskMaskSemanticPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type generateMusicGenerateMusicPostData = {
    body?: Body_generate_music_generate_music_post;
    path?: never;
    query?: never;
    url: '/generate/music';
};

export type generateMusicGenerateMusicPostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type generateMusicGenerateMusicPostError = generateMusicGenerateMusicPostErrors[keyof generateMusicGenerateMusicPostErrors];

export type generateMusicGenerateMusicPostResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type generateMusicGenerateMusicPostResponse = generateMusicGenerateMusicPostResponses[keyof generateMusicGenerateMusicPostResponses];

export type generateSoundEffectGenerateSoundEffectPostData = {
    body: Body_generate_sound_effect_generate_sound_effect_post;
    path?: never;
    query?: never;
    url: '/generate/sound-effect';
};

export type generateSoundEffectGenerateSoundEffectPostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type generateSoundEffectGenerateSoundEffectPostError = generateSoundEffectGenerateSoundEffectPostErrors[keyof generateSoundEffectGenerateSoundEffectPostErrors];

export type generateSoundEffectGenerateSoundEffectPostResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type generateSoundEffectGenerateSoundEffectPostResponse = generateSoundEffectGenerateSoundEffectPostResponses[keyof generateSoundEffectGenerateSoundEffectPostResponses];

export type generateImageGenerateImagePostData = {
    body: Body_generate_image_generate_image_post;
    path?: never;
    query?: never;
    url: '/generate/image';
};

export type generateImageGenerateImagePostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type generateImageGenerateImagePostError = generateImageGenerateImagePostErrors[keyof generateImageGenerateImagePostErrors];

export type generateImageGenerateImagePostResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type generateImageGenerateImagePostResponse = generateImageGenerateImagePostResponses[keyof generateImageGenerateImagePostResponses];

export type assembleAssemblePostData = {
    body: Body_assemble_assemble_post;
    path?: never;
    query?: never;
    url: '/assemble';
};

export type assembleAssemblePostErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type assembleAssemblePostError = assembleAssemblePostErrors[keyof assembleAssemblePostErrors];

export type assembleAssemblePostResponses = {
    /**
     * Successful Response
     */
    200: JobResponse;
};

export type assembleAssemblePostResponse = assembleAssemblePostResponses[keyof assembleAssemblePostResponses];
